---
title: "R_Facebook text mining"
author: "Minh Tan"
date: "2024-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Đọc vào file dữ liệu: summary(data)

```{r cars}
library(readxl)
data <- read_excel("C:/Users/Minh Tan/Downloads/fanpost_Lotteria Vietnam_W4.xlsx")
head(data)
View(data)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
# convert to a data frame
df <- data$message
head(df)

# build a corpus
myCorpus <- Corpus(VectorSource(df))

# convert to lower case
myCorpus <- tm_map(myCorpus, tolower)

```

```{r}
# remove punctuations and numbers
myCorpus <- tm_map(myCorpus, removePunctuation) 
myCorpus <- tm_map(myCorpus, removeNumbers)
```

```{r}
# make stopwords list
myStopwords <- c("thì", "mà", "là")
# remove stopwords
myCorpus <- tm_map(myCorpus, removeWords, myStopwords)
```

```{r}
# keep a copy of corpus myCorpusCopy <- myCorpus # stem words
#myCorpus <- tm_map(myCorpus, stemDocument)
# stem completion
#myCorpus <- tm_map(myCorpus, stemCompletion,
#dictionary = myCorpusCopy)
# replace "miners" with "mining", because "mining" was
# first stemmed to "mine" and then completed to "miners"
#myCorpus <- tm_map(myCorpus, gsub, pattern="miners",
#replacement="mining") strwrap(myCorpus[320], width=55)
```
library(tm)

```{r}
# TDM
myTdm <- TermDocumentMatrix(myCorpus,control=list(wordLengths=c(1,Inf)))
# inspect frequent words
(freq.terms <- findFreqTerms(myTdm, lowfreq=300))
# Sắp xếp các từ theo thứ tự giảm dần của tần suất xuất hiện
sorted_freq <- sort(freq.terms, decreasing = TRUE)
```

```{r}
# which words are associated with 'lotteria'?
findAssocs(myTdm, "lotteria", 0.2)
# which words are associated with 'ngon'?
findAssocs(myTdm, "ngon", 0.2)
```

```{r}
#install.packages("Rtools")
#install.packages("graph")
#install.packages("Rgraphviz")

#library(graph) 
#library(Rgraphviz)

#################################################################################################################

library(tidyverse)
library(reshape2)

#Biểu đồ TDM
plot(myTdm, term=freq.terms, corThreshold=0.1, weighting=T)

top_n <- 10 
freq_df <- data.frame(word = names(freq), frequency = freq)
top_words <- head(freq_df, top_n)

# Vẽ biểu đồ
ggplot(top_words, aes(x = reorder(word, frequency), y = frequency)) +
  geom_col() +
  coord_flip() +
  xlab("Word") +
  ylab("Frequency") +
  ggtitle("Top Words in Term Document Matrix")

#################################################################################################################
library(wordcloud)
m <- as.matrix(myTdm)
freq <- sort(rowSums(m), decreasing=T)
wordcloud(words=names(freq), freq=freq, min.freq=300, random.order=F)
#################################################################################################################

## [1] "r reference card data mining now available cran list" 
## [2] "used r functions package data mining applications"
```

```{r}
library(lubridate)

# Chuyển đổi cột create_time thành POSIXct
data$create_time <- ymd_hms(data$create_time)
# Tách cột thời gian đăng bài thành ngày tháng năm và Giờ
data$Date <- as.Date(data$create_time)
data$Time <- format(as.POSIXct(data$create_time), format = "%H:%M:%S")
```

```{r}
data$Time <- strptime(data$Time, format = "%H:%M:%S")
data$Time <- as.POSIXct(data$Time)

ggplot(data, aes(x = Time, y = like)) +
  geom_point() +
  scale_x_datetime(date_labels = "%H:%M:%S") +  
  labs(x = "Thời gian đăng bài", y = "Lượt like") +  
  ggtitle("Mối tương quan giữa thời gian đăng bài và lượt like")  

```

```{r}
ggplot(data, aes(x = Time, y = share)) +
  geom_point() +  
  scale_x_datetime(date_labels = "%H:%M:%S") +  
  labs(x = "Thời gian đăng bài", y = "Lượt share") +  
  ggtitle("Mối tương quan giữa thời gian đăng bài và lượt share")  
```

```{r}
ggplot(data, aes(x = Time, y = comment)) +
  geom_point() +  
  scale_x_datetime(date_labels = "%H:%M:%S") +  
  labs(x = "Thời gian đăng bài", y = "Comment") +  
  ggtitle("Mối tương quan giữa thời gian đăng bài và lượt comment")  
```

```{r}
# Chuyển đổi TDM thành ma trận dữ liệu numeric
tdm_numeric <- as.matrix(myTdm)

correlation_matrix <- cor(t(myTdm))

# Tính toán ma trận tương quan
correlation_matrix <- cor(subset_tdm)

# Vẽ biểu đồ heatmap từ ma trận tương quan
heatmap(correlation_matrix, Rowv=NA, Colv=NA, col = heat.colors(256))

```

